const Discord = module.require("discord.js");

module.exports = {
  name: "hujat",
  description: "Hujat seseorang",
  run: async (client, message, args) => {
    let target = message.mentions.members.first() || args.join(" ");
    let isBotOwner = require("../../config.json").OWNER_ID;
    if (args.length == 0) {
      return message.channel
        .send("sial, kau mau hujat udara..mention seseorang??")
        .then((msg) => setTimeout(() => msg.delete(), 2300));
    }
    var roasts = [
      "Bodoh dipelihara, kambing dipelihara bisa gemuk.",
      "Kau sangat bodoh.",
      "Cok jengkelin kali kau ini...",
      "Orang bodoh bisa berbahagia dengan kebodohannya.",
      "Kamu sama bodohnya dengan Spongebob.",
      "IQ KAMU lebih rendah dari udang.",
      "Kau sangat menyebalkan bahkan lalat pun menjauhi bau busukmu.",
      "Tolong pergi. bajingan ngapain disini?",
      "Jangan sembarangan cerita masalahmu pada teman. Karena teman juga punya teman bukan?",
      "Omongannya penuh kata-kata yang bijak dan benar, tapi kelakuannya belum sesuai dengan apa yang dikatakan sendiri.",
      "Jangan bangga apa yang diberikan orang tua, tapi banggalah apa yang telah kamu berikan pada orang tua..",
      "Yang namanya teman memang harus sering berbagi, tapi bukan berbagi pacar juga dong.",
      "Bukan masalah benar atau salah. Masalahnya adalah kamu yang merasa paling benar sendiri.",
      "Omonganmu kayak balon warna-warni, tapi sayang, isinya angin doang.",
      "Ini hidupku, kenapa kamu yang jadi sutradara?.",
      "Jangan sok menjauh sama seseorang yang belum berhasil, karena saat dia berhasil kamu bukan tipenya lagi.",
      "Kamu itu sama seperti uang receh, ya? Sudah bermuka dua, banyak orang yang tidak menganggap berharga..",
      "Wah kamu baik sekali, ya? Tapi, sayang pas ada maunya aja.",
      "Bekerjalah seperti tuyul, gak harus kelihatan, gak butuh pujian, gak gila jabatan, gak usah cari perhatian, tapi hasilnya jelas.",
      "Apa yang bisa disombongkan lagi saat semuanya diambil yang punya.",
      "Terus putar matamu. Mungkin kamu akan menemukan otak di belakang sana.",
      "Kamu terlihat seperti monyet, dan kamu juga berbau seperti monyet.",
      "Bahkan di antara para idiot kamu masih kurang.",
      "Kamu gagal bahkan ketika kamu sama sekali tidak melakukan apa-apa.",
      "Bercerminlah dahulu sebelum kamu membuat cermin orang lain.",
      "Itu orang yang bermuka dua, coba disumbangin satu dengan orang yang suka cari muka.",
      "Dasar gak tahu berterima kasih! Makanya hidupnya bisa menderita seperti itu.",
      "Kalau sudah berbicara tentang perasaan, sahabat pun berisiko jadi pelaku tikung menikung.",
      "Sekali-kali bolehlah menjadi orang yang jahat karena menjadi orang baik terus malah dimanfaatin sama teman sendiri..",
      "Kamu terdengar lebih baik dengan mulut tertutup.",
      "Otakmu tidak sebesar mulutmu.",
      "Aku tahu lelucon yang bagus! Kamu!",
      "Orang yang otaknya kosong paling banyak bicaranya.",
      "Apakah pantatmu cemburu dengan jumlah kotoran yang baru saja keluar dari mulutmu?",
      "Aku tidak sedang menghinamu, aku sedang mendeskripsikan dirimu..",
      "Oh, menderita? Makanya, jangan bikin susah orang.",
      "Akte kelahiran mu adalah surat permintaan maaf dari pabrik kondom.",
      "Tak seorang pun mempercayai pembohong. Sekalipun dia menceritakan kebenaran.",
      "Wajah itu dirawat, bukan diedit aplikasi.",
      "Sampah aja dibuang sembarangan, apalagi pacar.",
      "Nggak usah sok kaget, wajahmu nggak enak dilihat.",
      "Jangan suka ngurusin hidup gue, belum tentu gue mau kurus.",
      "Kalau mau ngurusin hidup saya, jangan lupa sekalian biaya hidup. Jangan tanggung-tanggung dong.",
      "Single itu prinsip, tapi jomblo itu nasib.",
      "Bodoh kok dipiara, kambing tuh dipiara biar gemuk.",
      "Daripada kamu mau makan teman, jangan lupa tambahkan nasi biar makin kenyang.",
      "Omonganmu seperti parfum isi ulang, wangi tapi palsu.",
      "Pasti kamu capek karena harus pakai make up di dua wajah sekaligus.",
      "Kebodohan bukanlah kejahatan jadi kamu bebas untuk pergi.",
      "Konon jika jodoh adalah tulang rusuk, maka mantan sudah menjadi fosil alias tulang belulang",
      "Kamu kok seperti tahi cicak neng, mukanya putih tapi lehernya hitam..",
      "Kata orang cinta itu buta, tapi nyatanya cinta bisa melihat mana yang tampan dan mana yang buruk rupa.",
      "Aku itu unlimited sedangkan kamu kaya kacang di pasar. Mudah ditemukan!",
      "Sendiri lebih baik daripada berdua jadi beban.",
      "Coba dulu sudah kredit rumah, pasti sudah lunas.",
      "Berjuangnya sama aku, giliran sudah berhasil kamu berpaling.",
      "Buanglah mantan pada orang yang lebih membutuhkan.",
      "Aku tau sebenarnya kamu itu GIGOLO kan",
      "Kamu terlihat seperti Artis bokep.",
      "Maaf aku alergi dengan yang namanya balikan sama mantan.",
      "Idiot over power.",
      "Apa benar mantan itu singkatan dari manis, tapi setan?",
      "Kalo kamu nggak bisa bikin orang lain ketawa, setidaknya jangan bikin orang lain menangis, kan begitu.",
      "Saya menemukan hanya ada satu cara untuk terlihat kurus: Kumpul bersama orang gendut.",
      "Kamu adalah bukti hidup bahwa TAI dapat berjalan.",
      "Baru putus aja udah punya pacar baru lagi, kok kamu tuh kaya rumah petak yang murah, sih.",
      "Nggak usah meninggi, kalau ukuran badanmu saja masih segitu.",
      "Selalu ikuti kata hatimu. Tapi jangan lupa bawa juga otakmu.",
      "Orang bodoh bisa berbahagia dengan kebodohannya.",
      "Hargai kedua orangtuamu, mereka berhasil lulus sekolah tanpa bantuan Google.",
      "Statusnya rohani, kelakuannya roh halus!",
      "Handphone jatuh, kita panik. Teman jatuh, kita tertawa terbahak-bahak",
      "Tetangga baru naik Avanza sudah banyak gaya, padahal yang naik sepeda jauh lebih kaya.",
      "Setiap kata ejekanmu. Kujadikan doa pembakar semangatku.",
      "Kerja freelance, duit banyak, dikira pakai babi ngepet. Sedangkan kamu kerja kantoran tapi nggak kaya-kaya. Gimana dong? Kan kasihan.",
      "Jika ada seorang teman mengatakan kamu 'PINTAR', jangan sombong. Belum tentu teman tersebut mengatakan yang sebenarnya.",
      "Contohlah tukang parkir, walaupun punya banyak mobil tapi dia nggak sombong! Karena dia tahu semua itu hanya titipan.",
      "Lihatlah ke atas sebagai motivasi bukan untuk jadi sombong, dan melihat ke bawah agar lebih bersyukur bukan untuk menjadi rendah diri.",
      "Kepala lo lebih besar dari mulut lo, tapi kenapa omong kosong lo lebih besar dari cara berpikir lo?",
      "Orang sombong biasanya suka mengatakan hal berlebihan yang sebenarnya tidak ada padanya.",
      "Bergayalah sesuai dompetmu, wahai anak muda.",
      "Sama-sama berasal dari tanah, sama-sama nginjek tanah dan bakal balik lagi ke tanah. Jadi buat apa sombong?",
      "Orang sombong sebenarnya pengecut karena ia tak berani bergaul dengan orang yang lebih hebat dengan dirinya.",
      "Yang lagi cantik jangan sombong, itu cantik sebentar doang. Tua dikit itu cantik sudah hilang, jadi jangan sombong ya cantik.",
      "Orang sombong itu ibarat orang yang berdiri di atas gunung. Dia melihat orang lain kecil, tapi dia tidak sadar orang lain melihatnya kecil juga.",
      "Mimpi itu akan terwujud bagi orang yang tahu waktu.",
      "Kenyataan itu bukan negeri dongeng, pantas saja kamu nggak pernah mau ke sana.",
      "Kata-katamu tak berarti ketika apa yang kau lakukan adalah sebaliknya.",
      "Kejujuran tidak mengorbankan apa pun, namun kebohongan akan menghabiskan segalanya.",
      "Berhati-hati dalam berkata, karena begitu terucap, dia hanya bisa dimaafkan, tapi tidak bisa dilupakan.",
      "Kebohongan yang diceritakan terlalu sering lama-lama akan terasa seperti kebenaran.",
      "Tak perlu mengkhawatirkan mereka yang membicarakanmu di belakang. Mereka ada di belakangmu karena suatu alasan.",
      "Teman datang seiring banyaknya kebutuhan.",
      "Maaf kalau aku menyakiti perasaanmu saat aku bilang kamu bodoh. Aku kira kamu sudah tahu.",
      "Seorang genius sejati takut terlihat tidak sempurna dan biasanya lebih suka diam daripada mengatakan sesuatu yang tidak berarti.",
      "Sayang, kalau kamu mau bermuka dua, paling tidak buatlah salah satunya terlihat cantik.",
      "Semoga suatu hari nanti hidupmu bakal seindah apa yang kamu pamerkan di Facebook.",
      "Miliki lebih dari yang kau tunjukkan, bicaralah lebih sedikit dari yang kamu tahu.",
      "Aku tak butuh teman yang berubah saat aku berubah dan mengangguk saat aku mengangguk. Bayanganku bisa melakukannya dengan lebih baik.",
      "Dunia itu tidak sempit. Kamu saja yang mainnya kurang jauh.",
    ];
    await message.channel.send(
      `${target}, ${roasts[Math.floor(Math.random() * roasts.length)]}`
    );
  },
};
