const Discord = module.require("discord.js");

module.exports = {
  name: "humor",
  description: "Kirim random humor",
  run: async (client, message, args) => {
    var jokes = [
      "Sebenarnya pelajaran matematika di Amerika lebih susah, karena dicampur dengan bahasa Inggris.",
      'Secapek-capeknya kerja, lebih capek nganggur.',
      'Ketika kamu merasa cobaan hidupmu terlalu berat, itu karena Tuhan tau kamu bisa mengatasinya. Kalo masih berat juga, diet dong ah.',
      'Gak papa deh bila kita beda kartu operator,asal nantinya nama kita ada di KARTU Keluarga yang sama.',
      'Jodoh itu kayak penjual gorengan. Ditungguin gak ada yang lewat, pas lagi gak pengen banyak yang lewat. eh pas mau disamperin udah banyak yang ngantri', // thanks to 30 Rock
      'Di mobil kamu ada yang wangi, kalau di mata kamu ada pelangi',
      "Penyesalan pasti datang di akhir, kalo di awal namanya pendaftaran.",
      'Manusia itu emang susah nyalahin diri sendiri. Leher pegel dibilang salah bantal.',
      "Aku mendadak Budek waktu kamu bilang *AKU SAYANG KAMU* Bukan kaga kedengeran tapi cuma pengen kamu ulangI terus.",
      'Mau mandi males, harus jalan ke kamar mandi, ada toilet online nggak yah biar di anterin',
      'Dompetku sama seperti bawang: membukanya membuatku menangis.',
      'Sekali terjatuh, bangunlah, dua kali, tetaplah tegar, jika jatuh lagi juga, makanya kalau jalan pakai mata..',
      "Meskipun sering dipetik, hikmah bukan termasuk dalam kategori alat musik.",
      "Kalo naik motor sama kamu pasti ditilang deh. Soalnya kita kan berTiga, Aku, Kamu, dan Cinta..",
      "Aku itu gak tau kamu itu siapa, terbuat dari apa. yang aku tahu itu cuma satu. kamu udah buat aku jatuh cinta.",
      "Cinta aku ke kamu dijamin tanpa pemanis buatan, pengawet buatan. semua alami murni dari hati..",
      "Kamu tahu, apa persamaan rasa sayangku ke kamu dengan matahari? Persamaannya adalah sama-sama terbit setiap hari dan hanya akan berakhir sampai kiamat.",
      'Kalau disuruh melupakanmu, aku harus ke kantor kelurahan dulu bikin surat keterangan tidak mampu.',
      "Apakah namamu WiFi? Soalnya aku bisa merasakan konektivitas.",
      "Madu di tangan kananmu, racun ditangan kirimu. Tapi, ingat jodoh tetap di tangan Tuhan.",
      "Makanan semahal apa pun nggak akan terasa mahal kalau kamu nggak membelinya.",
      "Dalam hidup pasti akan banyak rintangan. Karena kalau rantangan berarti itu katering.",
      "Kalau kamu sayang sama aku bilang dong. Aku bukan brankas yang butuh kode",
      "Selamat pagi semua! Jangan lupa bernafas, karena percuma tersenyum kalau nggak nafas",
      "Ketika hidup menutup pintu untukmu, maka buka lagi saja. Itu hanya pintu, dan begitulah cara kerjanya",
      'Motivator tak bisa membuatku rajin bekerja. Karena cuma cicilan dan tagihan yang mampu',
      'Seorang laki-laki sukses adalah yang bisa menghasilkan uang lebih dari yang dihabiskan istrinya. Seorang wanita sukses adalah yang bisa mencari laki laki seperti itu',
      "Jika masa depan tergantung pada mimpimu, maka perbanyaklah tidur",
      "Setinggi-tingginya burung bangau terbang, akhirnya jadi kecap juga.",
      "Orang bilang, ngopi sambil ngerokok itu nikmat. Tapi ternyata bohong, buktinya ini susah.",
      'Bercandanya bikin sayang, tapi sayangnya cuma bercanda',
      "Jika kamu sudah bikin kopi tapi ternyata masih tetap mengantuk, berarti kopinya belum kamu minum.",
      "Percayalah, kegagalan bukan suatu keberhasilan.",
      "Cowoknya cool, ceweknya hot, anaknya pasti dispenser.",
      "Sebenarnya pelajaran Matematika di Amerika terasa lebih susah karena dicampur bahasa Inggris.",
      "Bermimpilah sesuka hati tentang apa yang kamu inginkan, sebab itu hanya mimpi",
      "Kuliah lo ambil apa? Gue sih ambil hikmahnya aja.",
      'Tertawa bisa jadi obat terbaik. Tapi kalau kamu tertawa tanpa alasan yang jelas, mungkin kamu butuh obat!"',
      "Aku ingin jadi seperti ulat. Makan yang banyak, tidur cukup, dan terbangun dengan wujud yang indah",
      "Teman sejati tidak tersinggung saat kamu menghinanya. Mereka tersenyum dan balas menghinamu lebih parah lagi..",
      "Teman yang baik akan membantumu pindahan. Tapi teman terbaik akan membantumu memindahkan jasad!",
      "Taukah kamu apa yang lebih lucu dari 23? 24.",
      "Jomblo Bukan Berarti Homo.",
      "Jomblo itu ibarat emas, bila kelamaan tambah mahal hargannya.",
      "Satu bulan tak bertemu kamu, bagaikan 30 hari tanpa kamu.",
      "Cinta itu kaya martabak, manis, enak, gurih. Tapi kalo kebanyakan eneg.",
      "Wanita itu suka es cream dan coklat, namun lebih suka kepastian.",
      "“Cari wifi saja! kapan cari wife?”",
      "“Tatapanmu memanglah sederhana, namun dapat mengalihkan dunia.”",
      "“Aku sangat menyukai badut, dan aku akan bersedia menjadi badutmu setiap hari dengan bertingkah lucu untuk membuatmu tertawa setiap agar mampu melupakan air mata.”",
      "“Aku tak butuh hartamu, yang aku butuhkan hanyalah senyum bahagia dan canda tawamu saja sayangku.”",
      "“Jangan rindu berat, kamu gak akan kuat. Biar aku saja yang merindukanmu sekalipun bertambah berat badanku.”",
      "“Jika rindu ibarat uang, mungkin aku sudah menjadi orang terkaya di dunia karena telah menanggung rindu padamu.”",
      "“Jika sabar adalah barang yang diperjualbelikan, maka penantianku akan kehadiran dirimu ini sudah membuatku menjadi gelandangan.”",
      "“Jika kamu adalah bunga maka aku adalah sang lebah yang senantiasa membuatmu indah.”",
      "“Sayang .. Kita putus aja yaa? .. Emangnya kenapa? .. Kita uda gak cocok buat pacaran, kita cocoknya itu menikah.”",
      "“Lari pagi bikin badan sehat, lari di pikiran eneng bikin hati abang sehat.”",
      "“Sabar dan bodoh beda tipis, iya sabar ketika tahu pasangan kita lagi jalan sama orang lain.”",
      "“Aku bawa air di gelas, tapi selalu tumpah. Aku mah berantakan kalau gak ada kamu disisiku.”",
      "“Aku cinta padamu, ya memang itu urusanku. Dan bagaimana dirimu dan diriku? Terserah itu mah urusanmu.”",
      "“Saat bertemu denganmu jantung hatiku terasa berhenti berdetak, tapi kenapa gak mati – mati ya?”",
      "“Aku sangat menyukai badut, dan aku akan bersedia menjadi badutmu setiap hari dengan bertingkah lucu untuk membuatmu tertawa setiap agar mampu melupakan air mata.”",
      "“Aku tak butuh hartamu, yang aku butuhkan hanyalah senyum bahagia dan canda tawamu saja sayangku.”",
      "“Jangan rindu berat, kamu gak akan kuat. Biar aku saja yang merindukanmu sekalipun bertambah berat badanku.”",
      "“Cinta laksana pembodohan. Hanya karena namamu saja sudah membuatku gila.”",
      "“Katanya sih mending jadi temen aja biar gak nyakitin, tapi nyatanya belum apa – apa udah ngasih luka.”",
      "“Aku divonis menjadi terdakwa, karena telah mengambil hatimu. Dan hukumannya mencintaimu seumur hidupku.”",
      "“Kamu tahu cabe ? tahu lah ? apa bedanya sama kamu ? gatau. Emangnya apa ? kalau cabe panasnya cuman sampe di bibir, tapi kalo kamu bikin panasnya sampe ke hati.”",
      "“Aku ingin meminjam pelukan darimu, nanti ketika sudah puas aku akan mengembalikan pelukan itu.”",
      "“Jatuh cinta tak seperti jatuh dari pohon tomat.”",
      "“Cintaku seperti jam pasir, semakin hati kian terpenuhi maka otak akan kian tak terisi.”",
      "“Aku mencintaimu, seperti anak kecil yang suka ice cream.”",
      "“Ada tiga hal yang selalu menjadi keinginan wanita : kecupan, sentuhan dan pujian.”",
      "“Di bumi, gerak jatuh namanya graitasi, di hati namanya cinta selalu bersemi.”",
      "“Kamu sebaiknya selalu pakai wifi agar hati kita selalu terkoneksi.”",
      "“Yang .. sayangg .. pacaran uda hampir 5 tahun tapi kagak nikah – nikah, kayak cicilan mobil aja.”",
      "“Aku dan kamu bagaikan ambulan tanpa wiu uiwu”",
      "“Jika kamu bintang aku adalah matahari, jika kamu wajah biar aku yang jadi pemiliknya.”",
      "“Tatapanmu memanglah sederhana, namun dapat mengalihkan dunia.”",
      "“Jika rindu ibarat uang, mungkin aku sudah menjadi orang terkaya di dunia karena telah menanggung rindu padamu.”",
      "“Jika sabar adalah barang yang diperjualbelikan, maka penantianku akan kehadiran dirimu ini sudah membuatku menjadi gelandangan.”",
      "“Cinta itu gak bisa dihitung, kalaupun dihitung namanya bukan cinta tapi matematika.”",
      "“Kamu tahu alesanku suka sama kamu? Gak tau ? sama.”",
      "“Jika kamu adalah bunga maka aku adalah sang lebah yang senantiasa membuatmu indah.”",
      "“Sayang .. Kita putus aja yaa? .. Emangnya kenapa? .. Kita uda gak cocok buat pacaran, kita cocoknya itu menikah.”",
      "“Lari pagi bikin badan sehat, lari di pikiran eneng bikin hati abang sehat.”",
      "“Biar irit biaya ongkos, carilah pacar yang mau antar jemput.”",
      "“Satu tambah satu dua itu matematika, kalau aku tambah kamu bisa tiga, empat, lima dan seterusnya sampai bahagia dengan anak kita.”",
      "“Laut kan kusebrangi gunungpun akan kudaki hanya untukmu.”",
      "“Kamu adalah alasanku tetap bertahan di tanggal tua.”",
      "“Sebenarnya pacar orang itu juga pacar kita, karena kita kan juga orang.”",
      "“Untuk para jomblo, malam minggu di rumah aja, biar mengurangi kemacetan ibu kota.”",
      "“Hati – hati saat berkendara di jalan, karena jatuh di aspal tak seindah jatuh dalam pelukan.”",
      "“Gak papa kok kamu gendutan, hatiku masih muat tuh buat kamu.”",
      "“Jomblo sih strong, iyaa setres tak tertolong.”",
      "“Ketika ada hatiku dan hatimu di jalan maka jadinya ada dua hati yang hati – hati di jalan.”",
      "“Aku disini dan kamu disana, kamu sama dia aku sama siapa ?”",
      "“Tong tempat saja ada banyak isinya, masak hati aku satu aja dak ada isinya.”",
      "“Katanya gak akan ada kata terlambat untuk belajar. Belajar mencintai pacar orang misalnya.”",
      "“Gak papa kalau kamu gak ada pasangan, kalau kamu jatuh masih ada lantai yang akan menangkapmu.”",
      "“Katanya suka dalam diam itu mah kayak bianglala yang terus berputar, tapi nyatanya tidak kemana – mana eh malah jalan di tempat.”",
      "“Ada seseorang yang selalu memperhatikanmu, mempedulikanmu, bukan aku tapi seseorang. Hehe”",
      "“Kalau Anda jelek, Anda gak perlu takut untuk mencintai orang lain. Karena yang perlu takut adalah orang yang Anda cintai.”",
      "“Jangan terlalu banyak noleh kebelakang lihat masa lalu, nanti lehermu gak bisa muter ke depan.”",
      "“Katanya lebaran diundur setelah selesai puasa.”",
      "“Jika punya masalah jangan sampai menunggu waktu segera pecahkan, sebelum ada tulisan memecahkan berate harus membeli.”",
      "“Mbak, biar mulutnya gak suka ngomong kasar, kasih lotion aja biar kedengarannya halus.”",
      "“Cinta dan sayang tidak ada artinya apabila gak ada uangnya.”",
      "Wanita mau saja dimadu asalkan sang pria mau untuk di racun.”",
      "“”Saat dirimu memakai mobil yang wah aku hanya bisa menunduk, karena aku udah pakai pesawat terbang ..”",
      "“Giliran masih menjalin hubungan bilangnya beby – bebyan, eh pas putus jadinya babi – babian.”",
      "“Madu itu rasanya imbang sama racun. Karena dimadu itu sama aja rasanya kalo di racun.”",
      "“Kalo ngomong tuh jangan ketinggian, nanti di tabrak pesawat kapok loh.”",
      "“Sukses mah gak kayak isi bensin yang di isi mulai dari enol.”",
      "“Ga usah pasang status otw, takut nanti begal lagi baca. Kan bahaya.”",
      "“Ada yang bilang kamu adalah anaknya nona marni dia yang suka jahilin mirna.”",
      "“Dulu aku bercita – cita bisa s1, s2 sampai s3. Tapi kini, setelah bertemu denganmu aku hanya ingin sampai jenjang pelaminan saja.”",
      "“Uang itu ajaib, bisa mendatangkan dan menghilangkan teman dalam seketika.”",
      "“Sekarang ini cewek jamannow pakaiannya uda kalah sama si setan kuntilanak yang suka pake gamis panjang.”",
      "“Hatiku bukanlah sepatu yang baru, jadi gak perlu lah ya di injak – injak.”",
      "“Masih jam segini ko udah mandi aja sih ? iya soalnya uda ngerasa gerah ngeliat kamu deket sama dia.”",
      "“Panas terik matahari hari ini cukup menyengat, pas banget buat ngeringkan luka masa lalu yang tak kunjung sembuh.”",
      "“Baru bangun tidur nih, tapi belum sempet ngebuat kamu bangun kamu dari masa lalu.”",
      "“Ada yang lebih kejam daripada fitnah disini, yakni kentut tanpa adanya suara.”",
      "“Cewek mah gitu suka banget sama kaca, sampe spionpun selalu diarahin ke mukaya biar bisa ngaca terus sambil jalan.”",
      "“Aku pingin ngomong jujur sama kamu? Apa? Aku suka kamu sejak awal kita bertemu. Hahaha tapi aku ko enggak.”",
      "“Dinginnya udara malam ini memiliki persamaan sama kamu. Iya, kamu .. sama – sama bikin beku perasaanku.”",
      "“Fungsi hati itu ada dua, yaitu untuk menyimpan mineral dalam tubuh dan juga untuk menyimpan cintaku padamu.”",
      "“Ya kali di dunia ini semuanya harus terus mengalah, bahkan yang waras harus ngalah. Bisa – bisa yang jadi presiden orang gila.”",
      "“Kamu tahu gak ? tahu apa ? iya apa ? apa itu what ? apa ?”",
      "“Katanya cinta kok mendua ? katanya suka kok bikin luka ? sebenernya kamu ini manusia atau apa ?”",
      "“Aku dan kamu katanya kita, tapi kok nyatanya ada dia.”",
      "“Katanya cowok sih gak bisa nangis, nyatanya pas matanya di colok tetep nangis.”",
      "“Sukanya bilang selamat ke ibunya  kalo pas tanggal 21 Desember, giliran dipanggil namanya mau disuruh malah kabur.”",
      "“Jangan kemahalan neng kalau ngejual, nanti aku gak kuat bayarnya.”",
    ];
    await message.channel.send(jokes[Math.floor(Math.random() * jokes.length)]);
  },
};
